let x = 14.6

console.log(`Math.Pi          = ${Math.PI}`)
console.log(`Math.E           = ${Math.E}`)
console.log(`Math.round(${x}) = ${Math.round(x)}`)
console.log(`Math.floor(${x}) = ${Math.floor(x)}`)
console.log(`Math.ceil(${x})  = ${Math.ceil(x)}`)
console.log(`Math.trunc(${x}) = ${Math.trunc(x)}`)
console.log(`Math.pow(2, 3)   = ${Math.pow(2, 3)}`)
console.log(`Math.sqrt(625)   = ${Math.sqrt(625)}`)
console.log(`Math.log(e^3)    = ${Math.log(Math.E ** 3)}`)
console.log(`Math.abs(-125)   = ${Math.abs(-125)}`)
console.log(`Math.sign(-125)  = ${Math.sign(-125)}`)
console.log(`Math.max(-1, 10, 6)  = ${Math.max(-1, 10, 6)}`)
console.log(`Math.min(-1, 10, 6)  = ${Math.min(-1, 10, 6)}`)
console.log(`--------------`)
console.log(`Math.random()  = ${Math.random()}`)
console.log(`Math.floor(Math.random() * 6)  = ${Math.floor(Math.random() * 6)}`)
console.log(`Math.floor(Math.random() +100)  = ${Math.floor(Math.random() * 100)}`)
